######################################################################
#
# File name : post_system_simulate.do
# Created on: Sun Jun 26 21:19:06 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.post_system xil_defaultlib.glbl

do {post_system_wave.do}

view wave
view structure
view signals

do {post_system.udo}

run 1000ns
