######################################################################
#
# File name : post_system_wave.do
# Created on: Sun Jun 26 21:19:06 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
