######################################################################
#
# File name : post_system_compile.do
# Created on: Sun Jun 26 21:19:04 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib work
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/xil_defaultlib
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/dist_mem_gen_v8_0_10

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap xil_defaultlib msim/xil_defaultlib
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/datapath/Asynchronous_D_FF.v" \
"../../../CPU31.srcs/datapath/gpr.v" \
"../../../CPU31.srcs/datapath/nPC.v" \
"../../../CPU31.srcs/datapath/add4.v" \
"../../../CPU31.srcs/datapath/mux5.v" \
"../../../CPU31.srcs/datapath/mux.v" \
"../../../CPU31.srcs/datapath/II.v" \
"../../../CPU31.srcs/datapath/ext5.v" \
"../../../CPU31.srcs/datapath/ext18.v" \
"../../../CPU31.srcs/datapath/ext.v" \
"../../../CPU31.srcs/controller/dec.v" \
"../../../CPU31.srcs/controller/CU.v" \
"../../../CPU31.srcs/datapath/ALU.v" \
"../../../CPU31.srcs/datapath/add.v" \
"../../../CPU31.srcs/datapath/pcreg.v" \

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../CPU31.srcs/datapath/dm.v" \
"../../../CPU31.srcs/cpu31.v" \
"../../../CPU31.srcs/post_system.v" \

# compile glbl module
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -work xil_defaultlib "glbl.v"

quit -force

