# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/digital_logic/modelsim_10.4c/_modelsim/win32
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/digital_logic/project/CPU31/CPU31.cache/wt [current_project]
set_property parent.project_path D:/digital_logic/project/CPU31/CPU31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/digital_logic/project/CPU31/CPU31.srcs/test.coe
add_files D:/digital_logic/project/CPU31/CPU31.srcs/mips_31_mars_board_switch.coe
add_files -quiet d:/digital_logic/project/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files d:/digital_logic/project/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/Asynchronous_D_FF.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/gpr.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/nPC.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/add4.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/mux5.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/mux.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/II.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/ext5.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/ext18.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/ext.v
  D:/digital_logic/project/CPU31/CPU31.srcs/controller/dec.v
  D:/digital_logic/project/CPU31/CPU31.srcs/controller/CU.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/ALU.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/add.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/pcreg.v
  D:/digital_logic/project/CPU31/CPU31.srcs/sources_1/new/clock_wizard.v
  D:/digital_logic/project/CPU31/CPU31.srcs/seg7x16.v
  D:/digital_logic/project/CPU31/CPU31.srcs/datapath/dm.v
  D:/digital_logic/project/CPU31/CPU31.srcs/cpu31.v
  D:/digital_logic/project/CPU31/CPU31.srcs/sources_1/new/system.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/digital_logic/project/CPU31/CPU31.srcs/icf.xdc
set_property used_in_implementation false [get_files D:/digital_logic/project/CPU31/CPU31.srcs/icf.xdc]


synth_design -top system -part xc7a100tcsg324-1


write_checkpoint -force -noxdef system.dcp

catch { report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb }
